// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/ParserRobot202220.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class ParserRobot202220 {
  public static Object toSet(Object C) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v1=$newSet();
      $v2:for (Object x:GCollections.unmodifiableCollection(C)) {
        $v1.add(x);
      }
      $result=$v1;
      if (true) break $try;
      $line=3;
      $rethrow(new RuntimeException("The function \"toSet(C:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ParserRobot202220.class,"toSet",$line);
    }
    return $result;
  }
  public static IPushdownAutomaton createParser(Object A) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      Object Q=$fix($opIntvlY(0,9));
      $line=9;
      Object \u03A3=$fix($opUnionY(ParserRobot202220.toSet(A),GCollections.asSet(' ','\n')));
      $line=10;
      Object \u0393=$fix($opUnionY(GCollections.asSet('$'),ParserRobot202220.toSet(A)));
      $line=11;
      Object q_0=$fix(0);
      $line=12;
      Object F=$fix(GCollections.asSet(0));
      $line=13;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=14;
      Object SkipChars=$fix(GCollections.asSet(' ','\n'));
      $line=23;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'6')),new Object[]{"$"});
      $line=27;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,'%')),new Object[]{"$","$;v"});
      $line=28;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,'v')),new Object[]{"v"});
      $line=29;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,1,$cast(java.lang.String.class,',')),new Object[]{"$;","$;v"});
      $line=30;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,';')),new Object[]{";"});
      $line=34;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,2,$cast(java.lang.String.class,'[')),new Object[]{"(v"});
      $line=35;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,2,$cast(java.lang.String.class,'v')),new Object[]{"v"});
      $line=36;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,'(')),new Object[]{"$(","$(v"});
      $line=37;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,'(')),new Object[]{});
      $line=41;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,'v')),new Object[]{"v"});
      $line=42;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,',')),new Object[]{"$(","$(v"});
      $line=43;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,4,$cast(java.lang.String.class,')')),new Object[]{"("});
      $line=45;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,4,$cast(java.lang.String.class,')')),new Object[]{"$(","$"});
      $line=47;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,5,$cast(java.lang.String.class,'{')),new Object[]{"}"});
      $line=51;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,6,$cast(java.lang.String.class,'@')),new Object[]{")#("});
      $line=52;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,6,$cast(java.lang.String.class,'@')),new Object[]{")v("});
      $line=53;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,7,$cast(java.lang.String.class,'j')),new Object[]{")#,#("});
      $line=54;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,7,$cast(java.lang.String.class,'j')),new Object[]{")v,#("});
      $line=55;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,7,$cast(java.lang.String.class,'j')),new Object[]{")#,v("});
      $line=56;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,7,$cast(java.lang.String.class,'j')),new Object[]{")v,v("});
      $line=57;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,8,$cast(java.lang.String.class,'V')),new Object[]{")L("});
      $line=58;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,8,$cast(java.lang.String.class,'V')),new Object[]{")R("});
      $line=59;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,8,$cast(java.lang.String.class,'V')),new Object[]{")A("});
      $line=60;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,9,$cast(java.lang.String.class,'l')),new Object[]{")O("});
      $line=62;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,0,$cast(java.lang.String.class,'}')),new Object[]{"}"});
      $line=66;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,6,$cast(java.lang.String.class,'(')),new Object[]{"("});
      $line=67;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,6,$cast(java.lang.String.class,'#')),new Object[]{"#"});
      $line=68;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,6,$cast(java.lang.String.class,'v')),new Object[]{"v"});
      $line=69;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,6,$cast(java.lang.String.class,')')),new Object[]{")"});
      $line=70;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,5,$cast(java.lang.String.class,';')),new Object[]{});
      $line=74;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,7,$cast(java.lang.String.class,'(')),new Object[]{"("});
      $line=75;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,7,$cast(java.lang.String.class,'#')),new Object[]{"#"});
      $line=76;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,7,$cast(java.lang.String.class,'v')),new Object[]{"v"});
      $line=77;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,7,$cast(java.lang.String.class,',')),new Object[]{","});
      $line=78;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,7,$cast(java.lang.String.class,')')),new Object[]{")"});
      $line=79;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,5,$cast(java.lang.String.class,';')),new Object[]{});
      $line=83;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,8,$cast(java.lang.String.class,'(')),new Object[]{"("});
      $line=84;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,8,$cast(java.lang.String.class,'L')),new Object[]{"L"});
      $line=85;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,8,$cast(java.lang.String.class,'R')),new Object[]{"R"});
      $line=86;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,8,$cast(java.lang.String.class,'A')),new Object[]{"A"});
      $line=87;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,8,$cast(java.lang.String.class,')')),new Object[]{")"});
      $line=88;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,5,$cast(java.lang.String.class,';')),new Object[]{});
      $line=92;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(9,9,$cast(java.lang.String.class,'(')),new Object[]{"("});
      $line=93;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(9,9,$cast(java.lang.String.class,'O')),new Object[]{"O"});
      $line=94;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(9,9,$cast(java.lang.String.class,')')),new Object[]{")"});
      $line=95;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(9,5,$cast(java.lang.String.class,';')),new Object[]{});
      $line=97;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'9')),new Object[]{"$"});
      $line=101;
      for (Object $v3:GCollections.unmodifiableCollection(Q)) {
        Object q=$v3;
        $line=102;
        for (Object $v4:GCollections.unmodifiableCollection(SkipChars)) {
          Object s=$v4;
          $line=103;
          $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(q,q,$cast(java.lang.String.class,$opAdditY("",s))),new Object[]{});
        }
      }
      $line=108;
      $result=M;
      if (true) break $try;
      $line=109;
      $rethrow(new RuntimeException("The function \"createParser(A:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ParserRobot202220.class,"createParser",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
